services:
  ironbook_db:
    image: postgres:18
    container_name: ironbook_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ironbook
    volumes:
      - ironbook_data:/var/lib/postgresql/data
  ironbook_home:
    build:
      context: .
      dockerfile: apps/home/Dockerfile
    container_name: ironbook_home
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  ironbook_data:
