services:
  ironbook_home:
    build:
      context: .
      dockerfile: apps/home/Dockerfile
    container_name: ironbook_home
    ports:
      - "${HOST_PORT}:3000"
    environment:
      NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
      HOST_PORT: ${HOST_PORT}
    restart: unless-stopped