monorepo_root = true
[monorepo]
config_roots = [
    "apps/api",
    "apps/web",
    "apps/home",
    "apps/android",
    "apps/desktop"
]

[env]
MISE_DATA_DIR = "{{config_root}}/.mise"
MISE_STATE_DIR = "{{env.MISE_DATA_DIR}}/state"
MISE_CACHE_DIR = "{{env.MISE_DATA_DIR}}/cache"
MISE_INSTALLS_DIR = "{{env.MISE_DATA_DIR}}/installs"

[hooks.enter]
script = """
    echo 'Happy Development'
"""

[shell_alias]
root = "cd {{config_root}}"

[tasks."setup"]
description = "Install all dependencies"
run = [
  "mise //apps/home:setup",
  "mise //apps/api:setup",
  "mise //apps/web:setup",
  "mise //apps/android:setup",
  "mise //apps/desktop:setup",
]

[tools]
pre-commit = "4.6.2"
