monorepo_root = true
[monorepo]
config_roots = [
    "apps/api",
    "apps/web",
    "apps/home",
    "apps/android"
]

[env]
MISE_DATA_DIR = "{{config_root}}/.mise"
MISE_STATE_DIR = "{{env.MISE_DATA_DIR}}/state"
MISE_CACHE_DIR = "{{env.MISE_DATA_DIR}}/cache"
MISE_INSTALLS_DIR = "{{env.MISE_DATA_DIR}}/installs"

[tasks."setup"]
description = "Install all dependencies"
run = [
  "mise //apps/home:setup",
  "mise //apps/api:setup",
  "mise //apps/web:setup",
  "mise //apps/android:setup",
]
