@base_url = http://127.0.0.1:8000
@email = test@testmail.com
@password = testtest
@username = test

POST {{base_url}}/auth/register
Content-Type: application/json
{
    "email":"{{email}}",
    "username":"{{username}}"
    "password":"{{password}}"
}

POST {{base_url}}/auth/login
Content-Type: application/json
{
    "email":"{{email}}",
    "password":"{{password}}"
}
