[tools]
node = "24"
pnpm = "12.8.1"

[tasks."setup"]
description = "Setup NextJS Documentation Site"
run = "pnpm install"

[tasks."dev"]
description = "Run NextJS Dev Server"
run = "trap 'exit 0' INT TERM; pnpm --filter . dev"

[tasks."test"]
description = "Run tests for NextJS"
run = "pnpm exec vitest run --passWithNoTests"
